# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/emanuele/Scrivania/WebServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/emanuele/Scrivania/WebServer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/emanuele/Scrivania/WebServer/CMakeFiles /home/emanuele/Scrivania/WebServer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/emanuele/Scrivania/WebServer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

http_response.o: http_response.c.o

.PHONY : http_response.o

# target to build an object file
http_response.c.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/http_response.c.o
.PHONY : http_response.c.o

http_response.i: http_response.c.i

.PHONY : http_response.i

# target to preprocess a source file
http_response.c.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/http_response.c.i
.PHONY : http_response.c.i

http_response.s: http_response.c.s

.PHONY : http_response.s

# target to generate assembly for a file
http_response.c.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/http_response.c.s
.PHONY : http_response.c.s

lib/io.o: lib/io.c.o

.PHONY : lib/io.o

# target to build an object file
lib/io.c.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/lib/io.c.o
.PHONY : lib/io.c.o

lib/io.i: lib/io.c.i

.PHONY : lib/io.i

# target to preprocess a source file
lib/io.c.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/lib/io.c.i
.PHONY : lib/io.c.i

lib/io.s: lib/io.c.s

.PHONY : lib/io.s

# target to generate assembly for a file
lib/io.c.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/lib/io.c.s
.PHONY : lib/io.c.s

lib/ipc_sem.o: lib/ipc_sem.c.o

.PHONY : lib/ipc_sem.o

# target to build an object file
lib/ipc_sem.c.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/lib/ipc_sem.c.o
.PHONY : lib/ipc_sem.c.o

lib/ipc_sem.i: lib/ipc_sem.c.i

.PHONY : lib/ipc_sem.i

# target to preprocess a source file
lib/ipc_sem.c.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/lib/ipc_sem.c.i
.PHONY : lib/ipc_sem.c.i

lib/ipc_sem.s: lib/ipc_sem.c.s

.PHONY : lib/ipc_sem.s

# target to generate assembly for a file
lib/ipc_sem.c.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/lib/ipc_sem.c.s
.PHONY : lib/ipc_sem.c.s

lib/lock_fcntl.o: lib/lock_fcntl.c.o

.PHONY : lib/lock_fcntl.o

# target to build an object file
lib/lock_fcntl.c.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/lib/lock_fcntl.c.o
.PHONY : lib/lock_fcntl.c.o

lib/lock_fcntl.i: lib/lock_fcntl.c.i

.PHONY : lib/lock_fcntl.i

# target to preprocess a source file
lib/lock_fcntl.c.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/lib/lock_fcntl.c.i
.PHONY : lib/lock_fcntl.c.i

lib/lock_fcntl.s: lib/lock_fcntl.c.s

.PHONY : lib/lock_fcntl.s

# target to generate assembly for a file
lib/lock_fcntl.c.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/lib/lock_fcntl.c.s
.PHONY : lib/lock_fcntl.c.s

lib/logging.o: lib/logging.c.o

.PHONY : lib/logging.o

# target to build an object file
lib/logging.c.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/lib/logging.c.o
.PHONY : lib/logging.c.o

lib/logging.i: lib/logging.c.i

.PHONY : lib/logging.i

# target to preprocess a source file
lib/logging.c.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/lib/logging.c.i
.PHONY : lib/logging.c.i

lib/logging.s: lib/logging.c.s

.PHONY : lib/logging.s

# target to generate assembly for a file
lib/logging.c.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/lib/logging.c.s
.PHONY : lib/logging.c.s

lib/lru-cache.o: lib/lru-cache.c.o

.PHONY : lib/lru-cache.o

# target to build an object file
lib/lru-cache.c.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/lib/lru-cache.c.o
.PHONY : lib/lru-cache.c.o

lib/lru-cache.i: lib/lru-cache.c.i

.PHONY : lib/lru-cache.i

# target to preprocess a source file
lib/lru-cache.c.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/lib/lru-cache.c.i
.PHONY : lib/lru-cache.c.i

lib/lru-cache.s: lib/lru-cache.c.s

.PHONY : lib/lru-cache.s

# target to generate assembly for a file
lib/lru-cache.c.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/lib/lru-cache.c.s
.PHONY : lib/lru-cache.c.s

parser.o: parser.c.o

.PHONY : parser.o

# target to build an object file
parser.c.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/parser.c.o
.PHONY : parser.c.o

parser.i: parser.c.i

.PHONY : parser.i

# target to preprocess a source file
parser.c.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/parser.c.i
.PHONY : parser.c.i

parser.s: parser.c.s

.PHONY : parser.s

# target to generate assembly for a file
parser.c.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/parser.c.s
.PHONY : parser.c.s

server.o: server.c.o

.PHONY : server.o

# target to build an object file
server.c.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server.c.o
.PHONY : server.c.o

server.i: server.c.i

.PHONY : server.i

# target to preprocess a source file
server.c.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server.c.i
.PHONY : server.c.i

server.s: server.c.s

.PHONY : server.s

# target to generate assembly for a file
server.c.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server.c.s
.PHONY : server.c.s

sig_handler.o: sig_handler.c.o

.PHONY : sig_handler.o

# target to build an object file
sig_handler.c.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/sig_handler.c.o
.PHONY : sig_handler.c.o

sig_handler.i: sig_handler.c.i

.PHONY : sig_handler.i

# target to preprocess a source file
sig_handler.c.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/sig_handler.c.i
.PHONY : sig_handler.c.i

sig_handler.s: sig_handler.c.s

.PHONY : sig_handler.s

# target to generate assembly for a file
sig_handler.c.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/sig_handler.c.s
.PHONY : sig_handler.c.s

thread_job.o: thread_job.c.o

.PHONY : thread_job.o

# target to build an object file
thread_job.c.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/thread_job.c.o
.PHONY : thread_job.c.o

thread_job.i: thread_job.c.i

.PHONY : thread_job.i

# target to preprocess a source file
thread_job.c.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/thread_job.c.i
.PHONY : thread_job.c.i

thread_job.s: thread_job.c.s

.PHONY : thread_job.s

# target to generate assembly for a file
thread_job.c.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/thread_job.c.s
.PHONY : thread_job.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... server"
	@echo "... http_response.o"
	@echo "... http_response.i"
	@echo "... http_response.s"
	@echo "... lib/io.o"
	@echo "... lib/io.i"
	@echo "... lib/io.s"
	@echo "... lib/ipc_sem.o"
	@echo "... lib/ipc_sem.i"
	@echo "... lib/ipc_sem.s"
	@echo "... lib/lock_fcntl.o"
	@echo "... lib/lock_fcntl.i"
	@echo "... lib/lock_fcntl.s"
	@echo "... lib/logging.o"
	@echo "... lib/logging.i"
	@echo "... lib/logging.s"
	@echo "... lib/lru-cache.o"
	@echo "... lib/lru-cache.i"
	@echo "... lib/lru-cache.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
	@echo "... sig_handler.o"
	@echo "... sig_handler.i"
	@echo "... sig_handler.s"
	@echo "... thread_job.o"
	@echo "... thread_job.i"
	@echo "... thread_job.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

